### ISSUE TITLE
Error: invalid filename

### ISSUE THREAD

**Issue by PenguinM** [CyrilCommando/SankakuCacher#10]
When the tag contains “:"  it prompts an invalid filename, but in fact, this tag can be found. 
For example, date:<=2023-08-01

**Comment by CyrilCommando** [comment]
So, you're right about the error but not the character. I do things like voted:x or fav:x all the time. I had never used the date tag before so I didn't know it included the = and <> characters. Those would cause the error. 

I'll fix it asap. Thanks for telling me.

**Comment by CyrilCommando** [comment]
Alright, it's done. Download from the master branch.

**Comment by PenguinM** [comment]
Impressive repair speed! XD However, I'm currently using version 1.10.1 due to the fact that using v2 or the master branch plugins results in an error : "Could not establish connection. Receiving end does not exist."

**Comment by CyrilCommando** [comment]
Ok I managed to recreate that error. It must be a chrome thing. It only happens on chrome beyond 115 maybe. I tested for any issues and didn't find any so the error must be benign. I'll keep testing but I don't expect to find any and Windows 10 managed to brutally slaughter my entire PC while I was booting it to test for this very issue. I may be delayed. Lol.

I recommend to use the master branch. There will be issues otherwise especially with 1.10 because they've launched tons of changes that introduced issues since then. Like the addition of the AI panel up top.

**Comment by PenguinM** [comment]
That was crazy lol. My environment is Windows 11 x64 with Chrome version 116. I tried various versions from 115 down to 98 until it finally worked. XD

The AI panel did indeed lead to download offset, but now it's perfectly resolved. Nice work!
