### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by ghost** [CyrilCommando/SankakuCacher#2]
I downloaded it but cant open the file and use them

**Comment by CyrilCommando** [comment]
You need to extract the folder somewhere, then enable "developer mode" on the top right of Chrome's extensions screen. Click "Load unpacked", then select the folder you extracted. 
![image](https://user-images.githubusercontent.com/44797228/100551811-c0e1f500-3248-11eb-827e-79da1e948a20.png)

Unfortunately, Chrome doesn't allow easy installation via .crx from outside the Web Store anymore.

**Comment by ghost** [comment]
So what can I do?

**Comment by CyrilCommando** [comment]
You do what I told you.

**Comment by ghost** [comment]
I did and it gives error

**Comment by ghost** [comment]
Like all is set up but when i click download it does nothing

**Comment by CyrilCommando** [comment]
Make sure you're using the latest version. There was an issue a while ago where it wasn't downloading properly. Beyond that, I'll need more details. Do you have an error you can screenshot? Which download button are you clicking? What filetype is the media you're downloading?

**Comment by ghost** [comment]
I am on a link to download videos and images, so I click the cacher next to my extensions and click download.Would I check window on the extension or auto downalod or arrange files?

**Comment by CyrilCommando** [comment]
It only works on urls with the format https://chan.sankakucomplex.com/post/show/*. aka, pages like this
![image](https://user-images.githubusercontent.com/44797228/100556194-20023280-3266-11eb-98c7-2ef09f03fab4.png)

This isn't for beta sankaku or any other page.

**Comment by ghost** [comment]
I did, Do I paste username or tag?

**Comment by CyrilCommando** [comment]
Through all this, I still had no idea what button you were pressing... So you're pressing the "Download Tags" button under "Tags to download" section. That doesn't work because it requires a bunch of api calls or html parsing and sankaku broke the danbooru api literally as hard as possible. I wrote that it didn't work in a release many months ago but I didn't make it exceptionally clear everywhere else. So I'll make a list of things that currently don't work right here and I may put it in the description.

Arrange files doesn't work
Tags to download/Mass download doesn't work
Delete all downloaded images doesn't work

**Comment by ghost** [comment]
Ok, so only works to downloads by click each image? I did that and it work, I was hoping for mass but tis will do
