### ISSUE TITLE
Getting some manifest on v2, tried v3 failed horrible on troubleshooting xD

### ISSUE THREAD

**Issue by fluffyjin** [CyrilCommando/SankakuCacher#7]
Hello Friend, I noticed that there are some manifest version errors just wanted to post for awareness. I noticed that v1.52 when opening multiple tabs its smooth while the latest version 1.10.1 seems to lag when opening more than 10 tabs on chrome. Let me know how I can help. Thanks, love the extension will support with donations if possible for long term development.

**Comment by fluffyjin** [comment]
I quit lol. Failed horrible trying to migrate to v3. Gotta wait for the master of this cacher.

**Comment by CyrilCommando** [comment]
I'll fix the manifest soon. It'll be a while until it's deprecated though so I'm just putting it off. I'll definitely fix it before it's deprecated though.

As for the lag, I really don't know what it could be. I run Chrome with 30 tabs open daily and don't notice anything. 

The only thing it could be is a fix I put in to make the extension responsive on sankaku. It will rev up your CPU a lot when you first start the browser. I have to set a setting that makes Chrome look through the whole extension storage at start because it's bad at dealing with large storages. It will cause unresponsiveness for about a minute, and then go away.

**Comment by fluffyjin** [comment]
Boy am I glad to hear from you, thank you for the continuing support of this almighty extension! Wish I can get you a cup of java.
